apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: firstwebapp-k8s-deployment
  namespace: development
  labels: 
    app: firstwebapp-k8s
spec:
  replicas: 2  # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: firstwebapp-k8s
  template:
    metadata:
      labels:
        app: firstwebapp-k8s
    spec:
      containers:
        - image: adikrisnanugraha/jenkins-docker-hub # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          name: firstwebapp-k8s
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster

---


apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: firstwebapp-k8ssvc
spec:
  selector:
    app: firstwebapp-k8s
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: NodePort # type of the service.