apiVersion: v1
kind: Service
metadata:
  name: firstwebapp
  namespace: development
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30455
    protocol: TCP
  selector:
    app: firstwebapp